apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: "mongodb-data-dir"
        persistentVolumeClaim:
          claimName: "mongodb-pvc"
      containers:
      - name: mongodb
        image: mongo
        args: ["--dbpath","/data/db"]
        volumeMounts:
        - name: "mongodb-data-dir"
          mountPath: "/data/db"
        # env:
        # - name: MONGO_INITDB_ROOT_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongodb-creds
        #       key: username
        # - name: MONGO_INITDB_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongodb-creds
        #       key: password
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb-service
spec:
  type: NodePort
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Secret
data:
  username: YWRtaW51c2Vy
  password: cGFzc3dvcmQxMjM=
metadata:
  creationTimestamp: null
  name: mongodb-creds
