apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  grafana_dashboards.yaml: |-
    apiVersion: 1
    providers:
      - name: "Evidently Dashboards"
        orgId: 1
        folder: ""
        folderUid: ""
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: false
        options:
          path: /opt/grafana/dashboards
          foldersFromFilesStructure: true

  grafana_datasources.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
