apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion
spec:
  selector:
    matchLabels:
      app: orion
  replicas: 1
  template:
    metadata:
      labels:
        app: orion
    spec:
      volumes:
      - name: orion-pvc
        persistentVolumeClaim:
          claimName: orion-pvc
      containers:
      - name: api
        image: prefecthq/prefect:2.2.0-python3.9
        volumeMounts:
        - name: orion-pvc
          mountPath: '/root/.prefect'
        command: ["prefect", "orion", "start", "--host", "0.0.0.0", "--log-level", "WARNING"]
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: orion
  labels:
    app: orion
spec:
  ports:
    - port: 4200
      protocol: TCP
  selector:
    app: orion
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orion-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orion-ingress
spec:
  rules:
  - host: orion.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: orion
            port:
              number: 4200
